### ISSUE TITLE
Open orchestra panel

### ISSUE THREAD

**Issue by pdenis** [itkg/delay-event-bundle#25]
I think we can add the MHPS panel for delay-event channels in this bundle or create a specific open-orchestra-delay-event-bundle for this? 

Open orchestra panel may have also a simple log panel to see cron logs.

**Comment by clement-michelet** [comment]
I think we should have a specic open-orchestra-delay-event-admin-bundle.
We currently don't have any dependency to open-orchestra. We should stay in this configuration.
